Reworked sending
Chazmondo/AdvancementAPI pull request #9
Opened 2017-06-14 18:20 UTC by JarvisCraft

* Renamed to MessengerAdvancement as AdvancementAPI seems to be a better name for Singleton
+ Added .grant() and .revoke() methods
+ Added default values for variables
+ Added String-to-FrameType variants of input (supporting random values)
+ Returned setters without return type
+ Added @SuppressWarnings("unchecked") for .getJSON() method
- Deprecated .save() methods

2017-06-14 19:36 UTC, yannicklamprecht requested changes
Needs some changes. An idea is to create a inner class for the Builder Pattern!

2017-06-14 19:36 UTC, ysl3000 commented on AdvancementAPI.java
> +            setFrame(frames[(int)(Math.random()*(frames.length-1))]);
move `frames[(int)(Math.random()*(frames.length-1))]` to FrameType. Then you're able to do FrameType.random()

2017-06-14 19:36 UTC, ysl3000 commented on AdvancementAPI.java
> +            setFrame(frames[(int)(Math.random()*(frames.length-1))]);
same here -> setFrame(FrameType.random());

2017-06-14 19:36 UTC, ysl3000 commented on AdvancementAPI.java
> +        this.id = new NamespacedKey(ContentMakersPlugin.getInstance(), id);
Won't work this way. You've to pass the the JavaPlugin. `ContentMakersPlugin.getInstance()` only works with your plugin.

2017-06-14 19:36 UTC, ysl3000 commented on AdvancementAPI.java
> +    public void setIcon(String icon) {
Why adding this method? `withIcon(String icon)` does the work!

2017-06-14 19:36 UTC, ysl3000 commented on AdvancementAPI.java
> +    public void setDescription(String description) {
The same here. `withDescription(String description)` does it.

2017-06-14 19:36 UTC, ysl3000 commented on AdvancementAPI.java
> +    public void setBackground(String background) {
Why renaming it? The name `withBackground` has a reason. It implies thats make use of the BuilderPattern.

2017-06-14 20:59 UTC, JarvisCraft commented on AdvancementAPI.java
> +        this.id = new NamespacedKey(ContentMakersPlugin.getInstance(), id);
Here my bad
Forgotten to change back to norm

2017-06-14 21:01 UTC, JarvisCraft commented on AdvancementAPI.java
> +        this.id = new NamespacedKey(ContentMakersPlugin.getInstance(), id);
Will fix in a few minutes (when I'm from PC)

2017-06-14 21:02 UTC, JarvisCraft commented on AdvancementAPI.java
> +    public void setIcon(String icon) {
About setters explained above - just to make the Api fit in cases when it's not necessary to have return
Though it's a thing to discuss

2017-06-14 21:04 UTC, JarvisCraft commented
Will update to 1.2 soon fixing issues with wrong Plugin and Moving *random* to enum

2017-06-14 21:45 UTC, JarvisCraft commented
As said before:
* replaced ContentMakers with JavaPlugin (plus changed this constructor)
+ made `RANDOM()` into enum inside of `FrameType`

Thanks to @ysl3000 

//PS setters are still a thing to discuss as .with<NAME>'s don't seem to fit in those cases where value is only set for one param. I suggest:
* making smth. like `.with<NAME>() { .set<NAME>; return(this); }`
OR simply having only .<NAME>()'s
//PPS I'm also planning to add the `Map<String, AdvancementAPI>` (mentioned in Spigot discussion) as static member here and (probably) add "safe-show"

2017-06-14 22:30 UTC, ysl3000 commented
Do you know Lombok ? I tested how good the Builder is working for our problem and it is working really well. https://github.com/Craftstuebchen/AdvancementAPI/blob/master/src/test/java/AdvancementAPITest.java

https://github.com/Craftstuebchen/AdvancementAPI/blob/master/src/main/java/io/chazza/advancementapi/AdvancementAPI.java

2017-06-14 22:48 UTC, yannicklamprecht requested changes

2017-06-14 22:48 UTC, ysl3000 commented on AdvancementAPI.java
> +        Bukkit.getScheduler().runTaskLater(ContentMakersPlugin.getInstance(), new Runnable() {
Hey I found the same problem here. `ContentMakersPlugin.getInstance()`

2017-06-14 22:49 UTC, JarvisCraft commented on AdvancementAPI.java
> +        Bukkit.getScheduler().runTaskLater(ContentMakersPlugin.getInstance(), new Runnable() {
LoL
One minute

2017-06-14 22:57 UTC, JarvisCraft commented
+*Fixed .send() 

Gonna work on shortening tomorrow

//Sorry, it's 1:58 in Moscow now

2017-06-16 14:46 UTC, JarvisCraft commented
+ Added static `List<AdvancementAPI>` to hold all built Advancements generated during the following session
+ Added two static and one non-static `.build()` methods to replace all constructor-variants which also add AdvancementAPI-instances into static list
+ Added `.unbuild()` method to remove AdvancementAPI-instances from static list
+ Overwritten `.toString()` method`
+ Edited top JavaDocs (sorry if any mistakes)
* Renamed back into AdvancementAPI
* Renamed `.with<NAME>` methods into `.<NAME>` methods
- Removed AdvancementAPI(BukkitPlugin plugin, String name) constructor and made another one private
- Removed package
- Removed setters
- Removed unnecessary debug messages

2017-06-16 14:55 UTC, JarvisCraft commented
The new way to create a custom Advancement to better fit the OneClass-BuilderPattern:
`//In the given example I am creating a new Advancement-Announcement which will have a Unique ID "<PLUGINNAME>:announcement_breaker", will be shown once (to players player1 and player2), will have the diamond axe as an icon and will have a bold dark_red description "BREAK'EM'ALL":
AdvancementAPI.build(plugin, "announcement_breaker")
                .title("§4§lBREAK'EM'ALL")
                .icon("minecraft:diamond_axe")
                .show(player1, player2)
                .unbuild();
//.unbuild() in the end also returns AdvancementAPI so you can use it again (though any changes in it require server restart/reload new Unique ID)`

2017-06-16 15:09 UTC, merged